coverage:
  notify:
    wait_for_ci: true
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flag_management:
  default_rules:
    carryforward: true

flags:
  core:
    paths:
      - python/xorq/
    carryforward: true
  library:
    paths:
      - python/xorq/
    carryforward: true
  slow:
    paths:
      - python/xorq/
    carryforward: true
  databricks:
    paths:
      - python/xorq/
    carryforward: true
  snowflake:
    paths:
      - python/xorq/
    carryforward: true
  gcs:
    paths:
      - python/xorq/
    carryforward: true
  s3:
    paths:
      - python/xorq/
    carryforward: true
  examples:
    paths:
      - examples/
    carryforward: true

comment:
  layout: "reach,diff,flags,tree"
  require_changes: false
  require_base: false
  require_head: true

