# Table expressions

Tables are one of the core data structures in Ibis.

# Table { #xorq.vendor.ibis.expr.types.relations.Table }

```python
Table(arg)
```

An immutable and lazy dataframe.

Analogous to a SQL table or a pandas DataFrame. A table expression contains
an [ordered set of named columns](./schemas.qmd#ibis.expr.schema.Schema),
each with a single known type. Unless explicitly ordered with an
[`.order_by()`](./expression-tables.qmd#xorq.expr.types.relations.Table.order_by),
the order of rows is undefined.

Table immutability means that the data underlying an Ibis `Table` cannot be modified: every
method on a Table returns a new Table with those changes. Laziness
means that an Ibis `Table` expression does not run your computation every time you call one of its methods.
Instead, it is a symbolic expression that represents a set of operations
to be performed, which typically is translated into a SQL query. That
SQL query is then executed on a backend, where the data actually lives.
The result (now small enough to be manageable) can then be materialized back
into python as a pandas/pyarrow/python DataFrame/Column/scalar.

You will not create Table objects directly. Instead, you will create one

- from a pandas DataFrame, pyarrow table, Polars table, or raw python dicts/lists
  with [`xorq.memtable(df)`](./expression-tables.qmd#xorq.memtable)
- from an existing table in a data platform with
  [`connection.table("name")`](./expression-tables.qmd#xorq.backends.duckdb.Backend.table)
- from a file or URL, into a specific backend with
  [`connection.read_csv/parquet/json("path/to/file")`](../backends/duckdb.qmd#xorq.backends.duckdb.Backend.read_csv)
  (only some backends, typically local ones, support this)
- from a file or URL, into the default backend with
   [`ibis.read_csv/read_json/read_parquet("path/to/file")`](./expression-tables.qmd#ibis.read_csv)

## Methods

| Name | Description |
| --- | --- |
| [alias](#xorq.vendor.ibis.expr.types.relations.Table.alias) | Create a table expression with a specific name `alias`. |
| [as_scalar](#xorq.vendor.ibis.expr.types.relations.Table.as_scalar) | Inform ibis that the table expression should be treated as a scalar. |
| [count](#xorq.vendor.ibis.expr.types.relations.Table.count) | Compute the number of rows in the table. |
| [difference](#xorq.vendor.ibis.expr.types.relations.Table.difference) | Compute the set difference of multiple table expressions. |
| [distinct](#xorq.vendor.ibis.expr.types.relations.Table.distinct) | Return a Table with duplicate rows removed. |
| [dropna](#xorq.vendor.ibis.expr.types.relations.Table.dropna) | Deprecated - use `drop_null` instead. |
| [fillna](#xorq.vendor.ibis.expr.types.relations.Table.fillna) | Deprecated - use `fill_null` instead. |
| [filter](#xorq.vendor.ibis.expr.types.relations.Table.filter) | Select rows from `table` based on `predicates`. |
| [intersect](#xorq.vendor.ibis.expr.types.relations.Table.intersect) | Compute the set intersection of multiple table expressions. |
| [limit](#xorq.vendor.ibis.expr.types.relations.Table.limit) | Select `n` rows from `self` starting at `offset`. |
| [order_by](#xorq.vendor.ibis.expr.types.relations.Table.order_by) | Sort a table by one or more expressions. |
| [sample](#xorq.vendor.ibis.expr.types.relations.Table.sample) | Sample a fraction of rows from a table. |
| [select](#xorq.vendor.ibis.expr.types.relations.Table.select) | Compute a new table expression using `exprs` and `named_exprs`. |
| [sql](#xorq.vendor.ibis.expr.types.relations.Table.sql) | Run a SQL query against a table expression. |
| [union](#xorq.vendor.ibis.expr.types.relations.Table.union) | Compute the set union of multiple table expressions. |
| [view](#xorq.vendor.ibis.expr.types.relations.Table.view) | Create a new table expression distinct from the current one. |

### alias { #xorq.vendor.ibis.expr.types.relations.Table.alias }

```python
alias(alias)
```

Create a table expression with a specific name `alias`.

This method is useful for exposing an ibis expression to the underlying
backend for use in the
[`Table.sql`](#ibis.expr.types.relations.Table.sql) method.

::: {.callout-note}
## `.alias` will create a temporary view

`.alias` creates a temporary view in the database.

This side effect will be removed in a future version of ibis and **is
not part of the public API**.
:::

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type         | Description                  | Default    |
|--------|--------------|------------------------------|------------|
| alias  | [str](`str`) | Name of the child expression | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description         |
|--------|--------------------------------------------------------|---------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | An table expression |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.examples.penguins.fetch(deferred=False)
>>> expr = t.alias("pingüinos").sql('SELECT * FROM "pingüinos" LIMIT 5')
>>> expr
```


```{python}
#| echo: false
xo.options.interactive = False
```


### as_scalar { #xorq.vendor.ibis.expr.types.relations.Table.as_scalar }

```python
as_scalar()
```

Inform ibis that the table expression should be treated as a scalar.

Note that the table must have exactly one column and one row for this to
work. If the table has more than one column an error will be raised in
expression construction time. If the table has more than one row an
error will be raised by the backend when the expression is executed.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                | Description       |
|--------|-----------------------------------------------------|-------------------|
|        | [Scalar](`xorq.vendor.ibis.expr.types.uuid.Scalar`) | A scalar subquery |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.examples.penguins.fetch(deferred=False)
>>> heavy_gentoo = t.filter(t.species == "Gentoo", t.body_mass_g > 6200)
>>> from_that_island = t.filter(t.island == heavy_gentoo.select("island").as_scalar())
>>> from_that_island.species.value_counts().order_by("species")
```


```{python}
#| echo: false
xo.options.interactive = False
```


### count { #xorq.vendor.ibis.expr.types.relations.Table.count }

```python
count(where=None)
```

Compute the number of rows in the table.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                                                                                                   | Description                                               | Default   |
|--------|--------------------------------------------------------------------------------------------------------|-----------------------------------------------------------|-----------|
| where  | [ir](`xorq.vendor.ibis.expr.types`).[BooleanValue](`xorq.vendor.ibis.expr.types.BooleanValue`) \| None | Optional boolean expression to filter rows when counting. | `None`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                                 | Description                 |
|--------|----------------------------------------------------------------------|-----------------------------|
|        | [IntegerScalar](`xorq.vendor.ibis.expr.types.numeric.IntegerScalar`) | Number of rows in the table |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.memtable({"a": ["foo", "bar", "baz"]})
>>> t
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.count()
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.count(t.a != "foo")
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> type(t.count())
```


```{python}
#| echo: false
xo.options.interactive = False
```


### difference { #xorq.vendor.ibis.expr.types.relations.Table.difference }

```python
difference(table, *rest, distinct=True)
```

Compute the set difference of multiple table expressions.

The input tables must have identical schemas.

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type                                                   | Description                                                | Default    |
|----------|--------------------------------------------------------|------------------------------------------------------------|------------|
| table    | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | A table expression                                         | _required_ |
| *rest    | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | Additional table expressions                               | `()`       |
| distinct | [bool](`bool`)                                         | Only diff distinct rows not occurring in the calling table | `True`     |

#### See Also {.doc-section .doc-section-see-also}

[`ibis.difference`](./expression-tables.qmd#ibis.difference)

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description                                                  |
|--------|--------------------------------------------------------|--------------------------------------------------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | The rows present in `self` that are not present in `tables`. |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t1 = xo.memtable({"a": [1, 2]})
>>> t1
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t2 = xo.memtable({"a": [2, 3]})
>>> t2
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t1.difference(t2)
```


```{python}
#| echo: false
xo.options.interactive = False
```


### distinct { #xorq.vendor.ibis.expr.types.relations.Table.distinct }

```python
distinct(on=None, keep='first')
```

Return a Table with duplicate rows removed.

Similar to `pandas.DataFrame.drop_duplicates()`.

::: {.callout-note}
## Some backends do not support `keep='last'`
:::

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                                                                                                                                                                  | Description                                                                                                                                                                                   | Default   |
|--------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| on     | [str](`str`) \| [Iterable](`collections.abc.Iterable`)\[[str](`str`)\] \| [s](`xorq.vendor.ibis.selectors`).[Selector](`xorq.vendor.ibis.selectors.Selector`) \| None | Only consider certain columns for identifying duplicates. By default, deduplicate all of the columns.                                                                                         | `None`    |
| keep   | [Literal](`typing.Literal`)\[\'first\', \'last\'\] \| None                                                                                                            | Determines which duplicates to keep.  - `"first"`: Drop duplicates except for the first occurrence. - `"last"`: Drop duplicates except for the last occurrence. - `None`: Drop all duplicates | `'first'` |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> import xorq.examples as ex
>>> import xorq.selectors as s
>>> xo.options.interactive = True
>>> t = ex.penguins.fetch()
>>> t
```


```{python}
#| echo: false
xo.options.interactive = False
```


Compute the distinct rows of a subset of columns


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t[["species", "island"]].distinct().order_by(s.all())
```


```{python}
#| echo: false
xo.options.interactive = False
```


Drop all duplicate rows except the first


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.distinct(on=["species", "island"], keep="first").order_by(s.all())
```


```{python}
#| echo: false
xo.options.interactive = False
```


Drop all duplicate rows except the last


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.distinct(on=["species", "island"], keep="last").order_by(s.all())
```


```{python}
#| echo: false
xo.options.interactive = False
```


Drop all duplicated rows


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> expr = t.distinct(on=["species", "island", "year", "bill_length_mm"], keep=None)
>>> expr.count()
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.count()
```


```{python}
#| echo: false
xo.options.interactive = False
```


You can pass [`selectors`](./selectors.qmd) to `on`


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.distinct(on=~s.numeric())
```


```{python}
#| echo: false
xo.options.interactive = False
```


The only valid values of `keep` are `"first"`, `"last"` and [](`None`).


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
#| error: true
>>> t.distinct(on="species", keep="second")  
```


```{python}
#| echo: false
xo.options.interactive = False
```


### dropna { #xorq.vendor.ibis.expr.types.relations.Table.dropna }

```python
dropna(subset=None, how='any')
```

Deprecated - use `drop_null` instead.

### fillna { #xorq.vendor.ibis.expr.types.relations.Table.fillna }

```python
fillna(replacements)
```

Deprecated - use `fill_null` instead.

### filter { #xorq.vendor.ibis.expr.types.relations.Table.filter }

```python
filter(*predicates)
```

Select rows from `table` based on `predicates`.

#### Parameters {.doc-section .doc-section-parameters}

| Name       | Type                                                                                                                                                                                                                                                                                            | Description                                               | Default   |
|------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------|-----------|
| predicates | [ir](`xorq.vendor.ibis.expr.types`).[BooleanValue](`xorq.vendor.ibis.expr.types.BooleanValue`) \| [Sequence](`collections.abc.Sequence`)\[[ir](`xorq.vendor.ibis.expr.types`).[BooleanValue](`xorq.vendor.ibis.expr.types.BooleanValue`)\] \| [IfAnyAll](`xorq.vendor.ibis.selectors.IfAnyAll`) | Boolean value expressions used to select rows in `table`. | `()`      |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description               |
|--------|--------------------------------------------------------|---------------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | Filtered table expression |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.examples.penguins.fetch(deferred=False)
>>> t
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.filter([t.species == "Adelie", t.body_mass_g > 3500]).sex.value_counts().drop_null(
...     "sex"
... ).order_by("sex")
```


```{python}
#| echo: false
xo.options.interactive = False
```


### intersect { #xorq.vendor.ibis.expr.types.relations.Table.intersect }

```python
intersect(table, *rest, distinct=True)
```

Compute the set intersection of multiple table expressions.

The input tables must have identical schemas.

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type                                                   | Description                  | Default    |
|----------|--------------------------------------------------------|------------------------------|------------|
| table    | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | A table expression           | _required_ |
| *rest    | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | Additional table expressions | `()`       |
| distinct | [bool](`bool`)                                         | Only return distinct rows    | `True`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description                                                  |
|--------|--------------------------------------------------------|--------------------------------------------------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | A new table containing the intersection of all input tables. |

#### See Also {.doc-section .doc-section-see-also}

[`ibis.intersect`](./expression-tables.qmd#ibis.intersect)

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t1 = xo.memtable({"a": [1, 2]})
>>> t1
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t2 = xo.memtable({"a": [2, 3]})
>>> t2
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t1.intersect(t2)
```


```{python}
#| echo: false
xo.options.interactive = False
```


### limit { #xorq.vendor.ibis.expr.types.relations.Table.limit }

```python
limit(n, offset=0)
```

Select `n` rows from `self` starting at `offset`.

::: {.callout-note}
## The result set is not deterministic without a call to [`order_by`](#ibis.expr.types.relations.Table.order_by).
:::

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                 | Description                                                                                | Default    |
|--------|----------------------|--------------------------------------------------------------------------------------------|------------|
| n      | [int](`int`) \| None | Number of rows to include. If `None`, the entire table is selected starting from `offset`. | _required_ |
| offset | [int](`int`)         | Number of rows to skip first                                                               | `0`        |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description                                       |
|--------|--------------------------------------------------------|---------------------------------------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | The first `n` rows of `self` starting at `offset` |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.memtable({"a": [1, 1, 2], "b": ["c", "a", "a"]})
>>> t
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.limit(2)
```


```{python}
#| echo: false
xo.options.interactive = False
```


You can use `None` with `offset` to slice starting from a particular row


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.limit(None, offset=1)
```


```{python}
#| echo: false
xo.options.interactive = False
```


#### See Also {.doc-section .doc-section-see-also}

[`Table.order_by`](#ibis.expr.types.relations.Table.order_by)

### order_by { #xorq.vendor.ibis.expr.types.relations.Table.order_by }

```python
order_by(*by)
```

Sort a table by one or more expressions.

Similar to `pandas.DataFrame.sort_values()`.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Description                       | Default   |
|--------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------|-----------|
| by     | [str](`str`) \| [ir](`xorq.vendor.ibis.expr.types`).[Column](`xorq.vendor.ibis.expr.types.Column`) \| [s](`xorq.vendor.ibis.selectors`).[Selector](`xorq.vendor.ibis.selectors.Selector`) \| [Sequence](`collections.abc.Sequence`)\[[str](`str`)\] \| [Sequence](`collections.abc.Sequence`)\[[ir](`xorq.vendor.ibis.expr.types`).[Column](`xorq.vendor.ibis.expr.types.Column`)\] \| [Sequence](`collections.abc.Sequence`)\[[s](`xorq.vendor.ibis.selectors`).[Selector](`xorq.vendor.ibis.selectors.Selector`)\] \| None | Expressions to sort the table by. | `()`      |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description   |
|--------|--------------------------------------------------------|---------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | Sorted table  |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.memtable(
...     {
...         "a": [3, 2, 1, 3],
...         "b": ["a", "B", "c", "D"],
...         "c": [4, 6, 5, 7],
...     }
... )
>>> t
```


```{python}
#| echo: false
xo.options.interactive = False
```


Sort by b. Default is ascending. Note how capital letters come before lowercase


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.order_by("b")
```


```{python}
#| echo: false
xo.options.interactive = False
```


Sort in descending order


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.order_by(xo.desc("b"))
```


```{python}
#| echo: false
xo.options.interactive = False
```


You can also use the deferred API to get the same result


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> from xorq import _
>>> t.order_by(_.b.desc())
```


```{python}
#| echo: false
xo.options.interactive = False
```


Sort by multiple columns/expressions


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.order_by(["a", _.c.desc()])
```


```{python}
#| echo: false
xo.options.interactive = False
```


You can actually pass arbitrary expressions to use as sort keys.
For example, to ignore the case of the strings in column `b`


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.order_by(_.b.lower())
```


```{python}
#| echo: false
xo.options.interactive = False
```


This means that shuffling a Table is super simple


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.order_by(xo.random())
```


```{python}
#| echo: false
xo.options.interactive = False
```


[Selectors](./selectors.qmd) are allowed as sort keys and are a concise way to sort by
multiple columns matching some criteria


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq.selectors as s
>>> penguins = xo.examples.penguins.fetch(deferred=False)
>>> penguins[["year", "island"]].value_counts().order_by(s.startswith("year"))
```


```{python}
#| echo: false
xo.options.interactive = False
```


Use the [`across`](./selectors.qmd#ibis.selectors.across) selector to
apply a specific order to multiple columns


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> penguins[["year", "island"]].value_counts().order_by(
...     s.across(s.startswith("year"), _.desc())
... )
```


```{python}
#| echo: false
xo.options.interactive = False
```


### sample { #xorq.vendor.ibis.expr.types.relations.Table.sample }

```python
sample(fraction, *, method='row', seed=None)
```

Sample a fraction of rows from a table.

::: {.callout-note}
## Results may be non-repeatable

Sampling is by definition a random operation. Some backends support
specifying a `seed` for repeatable results, but not all backends
support that option. And some backends (duckdb, for example) do support
specifying a seed but may still not have repeatable results in all
cases.

In all cases, results are backend-specific. An execution against one
backend is unlikely to sample the same rows when executed against a
different backend, even with the same `seed` set.
:::

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type                                              | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Default    |
|----------|---------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| fraction | [float](`float`)                                  | The percentage of rows to include in the sample, expressed as a float between 0 and 1.                                                                                                                                                                                                                                                                                                                                                                                      | _required_ |
| method   | [Literal](`typing.Literal`)\[\'row\', \'block\'\] | The sampling method to use. The default is "row", which includes each row with a probability of `fraction`. If method is "block", some backends may instead perform sampling a fraction of blocks of rows (where "block" is a backend dependent definition). This is identical to "row" for backends lacking a blockwise sampling implementation. For those coming from SQL, "row" and "block" correspond to "bernoulli" and "system" respectively in a TABLESAMPLE clause. | `'row'`    |
| seed     | [int](`int`) \| None                              | An optional random seed to use, for repeatable sampling. The range of possible seed values is backend specific (most support at least `[0, 2**31 - 1]`). Backends that never support specifying a seed for repeatable sampling will error appropriately. Note that some backends (like DuckDB) do support specifying a seed, but may still not have repeatable results in all cases.                                                                                        | `None`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description                                        |
|--------|--------------------------------------------------------|----------------------------------------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | The input table, with `fraction` of rows selected. |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.memtable({"x": [1, 2, 3, 4], "y": ["a", "b", "c", "d"]})
>>> t
```


```{python}
#| echo: false
xo.options.interactive = False
```


Sample approximately half the rows, with a seed specified for
reproducibility.


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.sample(0.5, seed=1234)
```


```{python}
#| echo: false
xo.options.interactive = False
```


### select { #xorq.vendor.ibis.expr.types.relations.Table.select }

```python
select(*exprs, **named_exprs)
```

Compute a new table expression using `exprs` and `named_exprs`.

Passing an aggregate function to this method will broadcast the
aggregate's value over the number of rows in the table and
automatically constructs a window function expression. See the examples
section for more details.

For backwards compatibility the keyword argument `exprs` is reserved
and cannot be used to name an expression. This behavior will be removed
in v4.

#### Parameters {.doc-section .doc-section-parameters}

| Name        | Type                                                                                                                                                                                                                                           | Description                                                           | Default   |
|-------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------|-----------|
| exprs       | [ir](`xorq.vendor.ibis.expr.types`).[Value](`xorq.vendor.ibis.expr.types.Value`) \| [str](`str`) \| [Iterable](`collections.abc.Iterable`)\[[ir](`xorq.vendor.ibis.expr.types`).[Value](`xorq.vendor.ibis.expr.types.Value`) \| [str](`str`)\] | Column expression, string, or list of column expressions and strings. | `()`      |
| named_exprs | [ir](`xorq.vendor.ibis.expr.types`).[Value](`xorq.vendor.ibis.expr.types.Value`) \| [str](`str`)                                                                                                                                               | Column expressions                                                    | `{}`      |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description      |
|--------|--------------------------------------------------------|------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | Table expression |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t = xo.examples.penguins.fetch(deferred=False)
>>> t
```


```{python}
#| echo: false
xo.options.interactive = False
```


Simple projection


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.select("island", "bill_length_mm").head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


In that simple case, you could also just use python's indexing syntax


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t[["island", "bill_length_mm"]].head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


Projection by zero-indexed column position


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.select(t[0], t[4]).head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


Projection with renaming and compute in one call


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.select(next_year=t.year + 1).head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


You can do the same thing with a named expression, and using the
deferred API


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> from xorq import _
>>> t.select((_.year + 1).name("next_year")).head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


Projection with aggregation expressions


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t.select("island", bill_mean=t.bill_length_mm.mean()).head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


Projection with a selector


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq.selectors as s
>>> t.select(s.numeric() & ~s.cols("year")).head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


Projection + aggregation across multiple columns


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> from xorq import _
>>> t.select(s.across(s.numeric() & ~s.cols("year"), _.mean())).head()
```


```{python}
#| echo: false
xo.options.interactive = False
```


### sql { #xorq.vendor.ibis.expr.types.relations.Table.sql }

```python
sql(query, dialect=None)
```

Run a SQL query against a table expression.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type                 | Description                                                                                  | Default    |
|---------|----------------------|----------------------------------------------------------------------------------------------|------------|
| query   | [str](`str`)         | Query string                                                                                 | _required_ |
| dialect | [str](`str`) \| None | Optional string indicating the dialect of `query`. Defaults to the backend's native dialect. | `None`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description                |
|--------|--------------------------------------------------------|----------------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | An opaque table expression |

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> from xorq import _
>>> xo.options.interactive = True
>>> t = xo.examples.penguins.fetch(table_name="penguins", deferred=False)
>>> expr = t.sql(
...     """
...     SELECT island, mean(bill_length_mm) AS avg_bill_length
...     FROM penguins
...     GROUP BY 1
...     ORDER BY 2 DESC
...     """
... )
>>> expr
```


```{python}
#| echo: false
xo.options.interactive = False
```


Mix and match ibis expressions with SQL queries


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t = xo.examples.penguins.fetch(table_name="penguins", deferred=False)
>>> expr = t.sql(
...     """
...     SELECT island, mean(bill_length_mm) AS avg_bill_length
...     FROM penguins
...     GROUP BY 1
...     ORDER BY 2 DESC
...     """
... )
>>> expr = expr.mutate(
...     island=_.island.lower(),
...     avg_bill_length=_.avg_bill_length.round(1),
... )
>>> expr
```


```{python}
#| echo: false
xo.options.interactive = False
```


Because ibis expressions aren't named, they aren't visible to
subsequent `.sql` calls. Use the [`alias`](#ibis.expr.types.relations.Table.alias) method
to assign a name to an expression.


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> expr.alias("b").sql("SELECT * FROM b WHERE avg_bill_length > 40")
```


```{python}
#| echo: false
xo.options.interactive = False
```


#### See Also {.doc-section .doc-section-see-also}

[`Table.alias`](#ibis.expr.types.relations.Table.alias)

### union { #xorq.vendor.ibis.expr.types.relations.Table.union }

```python
union(table, *rest, distinct=False)
```

Compute the set union of multiple table expressions.

The input tables must have identical schemas.

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type                                                   | Description                  | Default    |
|----------|--------------------------------------------------------|------------------------------|------------|
| table    | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | A table expression           | _required_ |
| *rest    | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | Additional table expressions | `()`       |
| distinct | [bool](`bool`)                                         | Only return distinct rows    | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description                                           |
|--------|--------------------------------------------------------|-------------------------------------------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | A new table containing the union of all input tables. |

#### See Also {.doc-section .doc-section-see-also}

[`ibis.union`](./expression-tables.qmd#ibis.union)

#### Examples {.doc-section .doc-section-examples}


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> import xorq as xo
>>> xo.options.interactive = True
>>> t1 = xo.memtable({"a": [1, 2]})
>>> t1
```


```{python}
#| echo: false
xo.options.interactive = False
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t2 = xo.memtable({"a": [2, 3]})
>>> t2
```


```{python}
#| echo: false
xo.options.interactive = False
```

```python
>>> t1.union(t2)  # union all by default doctest: +SKIP
```


```{python}
#| echo: false

import xorq as xo
xo.options.interactive = True
```

```{python}
>>> t1.union(t2, distinct=True).order_by("a")
```


```{python}
#| echo: false
xo.options.interactive = False
```


### view { #xorq.vendor.ibis.expr.types.relations.Table.view }

```python
view()
```

Create a new table expression distinct from the current one.

Use this API for any self-referencing operations like a self-join.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                   | Description      |
|--------|--------------------------------------------------------|------------------|
|        | [Table](`xorq.vendor.ibis.expr.types.relations.Table`) | Table expression |