name: ci-pre-release

on:
  workflow_dispatch:

# we do not want more than one release workflow executing at the same time, ever
concurrency:
  group: release
  # cancelling in the middle of a release would create incomplete releases
  # so cancel-in-progress is false
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  release:
    name: release xorq to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pre-release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: publish package
        run: |
          uv build
          uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always

