name: ci-test-bigquery

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

permissions:
  contents: read


jobs:
  linux:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'ci-test-bigquery'
    strategy:
      matrix:
        target: ["x86_64"]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: download test data
        run: just download-data

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --extra bigquery --extra ibis --group dev --group test
        working-directory: ${{ github.workspace }}

      - name: Install DBC and BigQuery ADBC driver
        run: |
          curl -LsSf https://dbc.columnar.tech/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"
          dbc install bigquery

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093  # v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: pytest
        run: uv run --no-sync pytest --import-mode=importlib -m bigquery --cov --cov-report=xml -s -vv
        working-directory: ${{ github.workspace }}
        env:
          GOOGLE_BIGQUERY_PROJECT_ID: ${{ vars.GOOGLE_BIGQUERY_PROJECT_ID }}

      - name: Upload coverage reports to Codecov
        if: success()
        continue-on-error: true
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe  # v5.5.4
        with:
          flags: bigquery
          token: ${{ secrets.CODECOV_TOKEN }}
